new agents

diff --git a/Jenkins_Errorhandling b/Jenkins_Errorhandling
--- a/Jenkins_Errorhandling
+++ b/Jenkins_Errorhandling
@@ -3,8 +3,16 @@ pipeline {
     stages {
         stage('STAGE1') {
             steps {
-                echo "This is stage 1"
-                exit 1
+             script {
+                try {
+                     echo "This is stage 1"
+                     exit 1
+                }
+                catch (err) {
+                    echo "Error cought: ${err}"
+                    currentBuild.result = 'SUCCESS'
+                }
+             }
             }
         }
         stage('STAGE2') {
