new agents

diff --git a/Jenkins_errorhandling b/Jenkins_errorhandling
--- a/Jenkins_errorhandling
+++ b/Jenkins_errorhandling
@@ -3,16 +3,18 @@ pipeline {
     stages {
         stage('STAGE1') {
             steps {
-             script {
-                try {
-                     echo "This is stage 1"
-                     exit 1
+                script {
+                    try {
+                        sh '''
+                        echo "This is stage 1"
+                        exit 1
+                        '''
+                    }
+                    catch (err) {
+                        echo "Error cought: ${err}"
+                        currentBuild.result = 'SUCCESS'
+                    }
                 }
-                catch (err) {
-                    echo "Error cought: ${err}"
-                    currentBuild.result = 'SUCCESS'
-                }
-             }
             }
         }
         stage('STAGE2') {
